version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - msc-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "3000:3000"
    networks:
      - msc-network
    restart: unless-stopped

networks:
  msc-network:
    driver: bridge
